################################################################
# Global configuration
################################################################

debug = false
checkNewVersion = true
logLevel = "ERROR"
defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entrypoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
  [entryPoints.https.tls]

[retry]

################################################################
# Web configuration backend
################################################################

[web]

# Web administration port.
#
# Required
# Default: ":8080"
#
    address = ":8080"

    [web.auth.basic]
    users = ["admin:$2y$05$bUkLbh1xsgg5x5oJn4A4F.t3TD4.SbYh0oosFV2bFtK/n0c56mS36"]

################################################################
# Docker configuration backend
################################################################

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false
swarmmode = true

[acme]
email = "brian@bluerosedev.com"
storage = "/etc/traefik/acme.json"
entryPoint = "https"
OnHostRule = true
acmeLogging = true

[acme.httpChallenge]
entryPoint = "http"
